// ---- Auto-generated by radix4_mulgen/gen_booth_radix4.py ----
// Modified radix-4 Booth recoding.
// pp[i] is a compact two's-complement row; the top generator adds
// the missing sign-extension correction before the final CPA.
module BoothRadix4_32 (
  input  [31:0] x_in,
  input  [31:0] y_in,
  input            signed_op,
  output [33:0] pp0, pp1, pp2, pp3,
  output [33:0] pp4, pp5, pp6, pp7,
  output [33:0] pp8, pp9, pp10, pp11,
  output [33:0] pp12, pp13, pp14, pp15,
  output [33:0] pp16,
  output [16:0] pp_sign
);

  wire [33:0] x_ext;
  assign x_ext = {{2{signed_op & x_in[31]}}, x_in};
  wire [33:0] x_neg;
  assign x_neg = (~x_ext) + 1'b1;
  wire [33:0] x2_ext;
  assign x2_ext = {x_ext[32:0], 1'b0};
  wire [33:0] x2_neg;
  assign x2_neg = (~x2_ext) + 1'b1;

  wire [34:0] y_ext;
  assign y_ext = signed_op ? {{2{y_in[31]}}, y_in, 1'b0} : {2'b0, y_in, 1'b0};

  wire [2:0] code0;
  assign code0 = y_ext[2:0];
  wire [33:0] pp0_raw;
  assign pp0_raw = (code0 == 3'b000 || code0 == 3'b111) ? 34'b0 :
                      (code0 == 3'b001 || code0 == 3'b010) ? x_ext :
                      (code0 == 3'b011) ? x2_ext :
                      (code0 == 3'b100) ? x2_neg : x_neg;
  assign pp0 = pp0_raw;
  assign pp_sign[0] = pp0_raw[33];

  wire [2:0] code1;
  assign code1 = y_ext[4:2];
  wire [33:0] pp1_raw;
  assign pp1_raw = (code1 == 3'b000 || code1 == 3'b111) ? 34'b0 :
                      (code1 == 3'b001 || code1 == 3'b010) ? x_ext :
                      (code1 == 3'b011) ? x2_ext :
                      (code1 == 3'b100) ? x2_neg : x_neg;
  assign pp1 = pp1_raw;
  assign pp_sign[1] = pp1_raw[33];

  wire [2:0] code2;
  assign code2 = y_ext[6:4];
  wire [33:0] pp2_raw;
  assign pp2_raw = (code2 == 3'b000 || code2 == 3'b111) ? 34'b0 :
                      (code2 == 3'b001 || code2 == 3'b010) ? x_ext :
                      (code2 == 3'b011) ? x2_ext :
                      (code2 == 3'b100) ? x2_neg : x_neg;
  assign pp2 = pp2_raw;
  assign pp_sign[2] = pp2_raw[33];

  wire [2:0] code3;
  assign code3 = y_ext[8:6];
  wire [33:0] pp3_raw;
  assign pp3_raw = (code3 == 3'b000 || code3 == 3'b111) ? 34'b0 :
                      (code3 == 3'b001 || code3 == 3'b010) ? x_ext :
                      (code3 == 3'b011) ? x2_ext :
                      (code3 == 3'b100) ? x2_neg : x_neg;
  assign pp3 = pp3_raw;
  assign pp_sign[3] = pp3_raw[33];

  wire [2:0] code4;
  assign code4 = y_ext[10:8];
  wire [33:0] pp4_raw;
  assign pp4_raw = (code4 == 3'b000 || code4 == 3'b111) ? 34'b0 :
                      (code4 == 3'b001 || code4 == 3'b010) ? x_ext :
                      (code4 == 3'b011) ? x2_ext :
                      (code4 == 3'b100) ? x2_neg : x_neg;
  assign pp4 = pp4_raw;
  assign pp_sign[4] = pp4_raw[33];

  wire [2:0] code5;
  assign code5 = y_ext[12:10];
  wire [33:0] pp5_raw;
  assign pp5_raw = (code5 == 3'b000 || code5 == 3'b111) ? 34'b0 :
                      (code5 == 3'b001 || code5 == 3'b010) ? x_ext :
                      (code5 == 3'b011) ? x2_ext :
                      (code5 == 3'b100) ? x2_neg : x_neg;
  assign pp5 = pp5_raw;
  assign pp_sign[5] = pp5_raw[33];

  wire [2:0] code6;
  assign code6 = y_ext[14:12];
  wire [33:0] pp6_raw;
  assign pp6_raw = (code6 == 3'b000 || code6 == 3'b111) ? 34'b0 :
                      (code6 == 3'b001 || code6 == 3'b010) ? x_ext :
                      (code6 == 3'b011) ? x2_ext :
                      (code6 == 3'b100) ? x2_neg : x_neg;
  assign pp6 = pp6_raw;
  assign pp_sign[6] = pp6_raw[33];

  wire [2:0] code7;
  assign code7 = y_ext[16:14];
  wire [33:0] pp7_raw;
  assign pp7_raw = (code7 == 3'b000 || code7 == 3'b111) ? 34'b0 :
                      (code7 == 3'b001 || code7 == 3'b010) ? x_ext :
                      (code7 == 3'b011) ? x2_ext :
                      (code7 == 3'b100) ? x2_neg : x_neg;
  assign pp7 = pp7_raw;
  assign pp_sign[7] = pp7_raw[33];

  wire [2:0] code8;
  assign code8 = y_ext[18:16];
  wire [33:0] pp8_raw;
  assign pp8_raw = (code8 == 3'b000 || code8 == 3'b111) ? 34'b0 :
                      (code8 == 3'b001 || code8 == 3'b010) ? x_ext :
                      (code8 == 3'b011) ? x2_ext :
                      (code8 == 3'b100) ? x2_neg : x_neg;
  assign pp8 = pp8_raw;
  assign pp_sign[8] = pp8_raw[33];

  wire [2:0] code9;
  assign code9 = y_ext[20:18];
  wire [33:0] pp9_raw;
  assign pp9_raw = (code9 == 3'b000 || code9 == 3'b111) ? 34'b0 :
                      (code9 == 3'b001 || code9 == 3'b010) ? x_ext :
                      (code9 == 3'b011) ? x2_ext :
                      (code9 == 3'b100) ? x2_neg : x_neg;
  assign pp9 = pp9_raw;
  assign pp_sign[9] = pp9_raw[33];

  wire [2:0] code10;
  assign code10 = y_ext[22:20];
  wire [33:0] pp10_raw;
  assign pp10_raw = (code10 == 3'b000 || code10 == 3'b111) ? 34'b0 :
                      (code10 == 3'b001 || code10 == 3'b010) ? x_ext :
                      (code10 == 3'b011) ? x2_ext :
                      (code10 == 3'b100) ? x2_neg : x_neg;
  assign pp10 = pp10_raw;
  assign pp_sign[10] = pp10_raw[33];

  wire [2:0] code11;
  assign code11 = y_ext[24:22];
  wire [33:0] pp11_raw;
  assign pp11_raw = (code11 == 3'b000 || code11 == 3'b111) ? 34'b0 :
                      (code11 == 3'b001 || code11 == 3'b010) ? x_ext :
                      (code11 == 3'b011) ? x2_ext :
                      (code11 == 3'b100) ? x2_neg : x_neg;
  assign pp11 = pp11_raw;
  assign pp_sign[11] = pp11_raw[33];

  wire [2:0] code12;
  assign code12 = y_ext[26:24];
  wire [33:0] pp12_raw;
  assign pp12_raw = (code12 == 3'b000 || code12 == 3'b111) ? 34'b0 :
                      (code12 == 3'b001 || code12 == 3'b010) ? x_ext :
                      (code12 == 3'b011) ? x2_ext :
                      (code12 == 3'b100) ? x2_neg : x_neg;
  assign pp12 = pp12_raw;
  assign pp_sign[12] = pp12_raw[33];

  wire [2:0] code13;
  assign code13 = y_ext[28:26];
  wire [33:0] pp13_raw;
  assign pp13_raw = (code13 == 3'b000 || code13 == 3'b111) ? 34'b0 :
                      (code13 == 3'b001 || code13 == 3'b010) ? x_ext :
                      (code13 == 3'b011) ? x2_ext :
                      (code13 == 3'b100) ? x2_neg : x_neg;
  assign pp13 = pp13_raw;
  assign pp_sign[13] = pp13_raw[33];

  wire [2:0] code14;
  assign code14 = y_ext[30:28];
  wire [33:0] pp14_raw;
  assign pp14_raw = (code14 == 3'b000 || code14 == 3'b111) ? 34'b0 :
                      (code14 == 3'b001 || code14 == 3'b010) ? x_ext :
                      (code14 == 3'b011) ? x2_ext :
                      (code14 == 3'b100) ? x2_neg : x_neg;
  assign pp14 = pp14_raw;
  assign pp_sign[14] = pp14_raw[33];

  wire [2:0] code15;
  assign code15 = y_ext[32:30];
  wire [33:0] pp15_raw;
  assign pp15_raw = (code15 == 3'b000 || code15 == 3'b111) ? 34'b0 :
                      (code15 == 3'b001 || code15 == 3'b010) ? x_ext :
                      (code15 == 3'b011) ? x2_ext :
                      (code15 == 3'b100) ? x2_neg : x_neg;
  assign pp15 = pp15_raw;
  assign pp_sign[15] = pp15_raw[33];

  wire [2:0] code16;
  assign code16 = y_ext[34:32];
  wire [33:0] pp16_raw;
  assign pp16_raw = (code16 == 3'b000 || code16 == 3'b111) ? 34'b0 :
                      (code16 == 3'b001 || code16 == 3'b010) ? x_ext :
                      (code16 == 3'b011) ? x2_ext :
                      (code16 == 3'b100) ? x2_neg : x_neg;
  assign pp16 = pp16_raw;
  assign pp_sign[16] = pp16_raw[33];

endmodule
