// ---- Auto-generated by radix4_mulgen/gen_top_radix4.py ----
// pipelined top: input register plus Wallace, sign-extension CSA, and final-adder pipeline cuts
module CSA_66 (
  input  [65:0] a, b, c,
  output [65:0] sum_out,
  output [65:0] carry_out
);
  assign sum_out   = a ^ b ^ c;
  assign carry_out = (a & b) | (a & c) | (b & c);
endmodule

module TopMultiplier (
  input            clk,
  input            reset,
  input            mult,
  input  [31:0] x_in,
  input  [31:0] y_in,
  input            signed_op,
  output     [63:0] result_out,
  output           done
);

`ifndef MUL_DONE_LATENCY
`define MUL_DONE_LATENCY 4
`endif

  localparam integer MUL_DONE_LATENCY_C = `MUL_DONE_LATENCY;
  localparam integer MUL_BASE_LATENCY_C = 4;
  localparam integer MUL_EXTRA_LATENCY_C = (MUL_DONE_LATENCY_C > MUL_BASE_LATENCY_C) ?
                                           (MUL_DONE_LATENCY_C - MUL_BASE_LATENCY_C) : 0;

  wire [33:0] pp0;
  wire [33:0] pp1;
  wire [33:0] pp2;
  wire [33:0] pp3;
  wire [33:0] pp4;
  wire [33:0] pp5;
  wire [33:0] pp6;
  wire [33:0] pp7;
  wire [33:0] pp8;
  wire [33:0] pp9;
  wire [33:0] pp10;
  wire [33:0] pp11;
  wire [33:0] pp12;
  wire [33:0] pp13;
  wire [33:0] pp14;
  wire [33:0] pp15;
  wire [33:0] pp16;
  wire [16:0] pp_sign;

  reg [31:0] x_s0_q;
  reg [31:0] y_s0_q;
  reg        signed_s0_q;

  BoothRadix4_32 booth (
    .x_in(x_s0_q), .y_in(y_s0_q), .signed_op(signed_s0_q),
    .pp0(pp0),
    .pp1(pp1),
    .pp2(pp2),
    .pp3(pp3),
    .pp4(pp4),
    .pp5(pp5),
    .pp6(pp6),
    .pp7(pp7),
    .pp8(pp8),
    .pp9(pp9),
    .pp10(pp10),
    .pp11(pp11),
    .pp12(pp12),
    .pp13(pp13),
    .pp14(pp14),
    .pp15(pp15),
    .pp16(pp16),
    .pp_sign(pp_sign)
  );

  wire [65:0] wallace_sum, wallace_carry;
  WallaceTreeR4_32 wallace (
    .clk(clk), .reset(reset),
    .pp0(pp0),
    .pp1(pp1),
    .pp2(pp2),
    .pp3(pp3),
    .pp4(pp4),
    .pp5(pp5),
    .pp6(pp6),
    .pp7(pp7),
    .pp8(pp8),
    .pp9(pp9),
    .pp10(pp10),
    .pp11(pp11),
    .pp12(pp12),
    .pp13(pp13),
    .pp14(pp14),
    .pp15(pp15),
    .pp16(pp16),
    .opa(wallace_sum), .opb(wallace_carry)
  );

  reg        valid_s0_q;
  reg        valid_s1_q;
  reg        valid_s2_q;
  reg        valid_s3_q;
  reg        valid_s4_q;
  reg [16:0] pp_sign_s1_q;
  reg [65:0] wallace_sum_s2_q;
  reg [65:0] wallace_carry_s2_q;
  reg [65:0] signext_term_s2_q;
  reg [65:0] csa_sum_s3_q;
  reg [65:0] csa_carry_raw_s3_q;
  reg [63:0] result_s4_q;

  wire [65:0] signext_term;
  wire [65:0] csa_sum;
  wire [65:0] csa_carry_raw;
  wire [65:0] result_full;

  always @(posedge clk or posedge reset) begin
    if (reset) begin
      x_s0_q <= 32'b0;
      y_s0_q <= 32'b0;
      signed_s0_q <= 1'b0;
      valid_s0_q <= 1'b0;
      valid_s1_q <= 1'b0;
      valid_s2_q <= 1'b0;
      valid_s3_q <= 1'b0;
      valid_s4_q <= 1'b0;
      pp_sign_s1_q <= 17'b0;
      wallace_sum_s2_q <= 66'b0;
      wallace_carry_s2_q <= 66'b0;
      signext_term_s2_q <= 66'b0;
      csa_sum_s3_q <= 66'b0;
      csa_carry_raw_s3_q <= 66'b0;
      result_s4_q <= 64'b0;
    end else begin
      if (mult) begin
        x_s0_q <= x_in;
        y_s0_q <= y_in;
        signed_s0_q <= signed_op;
      end
      valid_s0_q <= mult;

      valid_s1_q <= valid_s0_q;
      pp_sign_s1_q <= pp_sign;

      valid_s2_q <= valid_s1_q;
      wallace_sum_s2_q <= wallace_sum;
      wallace_carry_s2_q <= wallace_carry;
      signext_term_s2_q <= signext_term;

      valid_s3_q <= valid_s2_q;
      csa_sum_s3_q <= csa_sum;
      csa_carry_raw_s3_q <= csa_carry_raw;

      valid_s4_q <= valid_s3_q;
      result_s4_q <= result_full[63:0];
    end
  end

  wire [65:0] sx_term0;
  assign sx_term0 = pp_sign_s1_q[0] ? 66'h3fffffffc00000000 : 66'b0;
  wire [65:0] sx_term1;
  assign sx_term1 = pp_sign_s1_q[1] ? 66'h3fffffff000000000 : 66'b0;
  wire [65:0] sx_term2;
  assign sx_term2 = pp_sign_s1_q[2] ? 66'h3ffffffc000000000 : 66'b0;
  wire [65:0] sx_term3;
  assign sx_term3 = pp_sign_s1_q[3] ? 66'h3ffffff0000000000 : 66'b0;
  wire [65:0] sx_term4;
  assign sx_term4 = pp_sign_s1_q[4] ? 66'h3fffffc0000000000 : 66'b0;
  wire [65:0] sx_term5;
  assign sx_term5 = pp_sign_s1_q[5] ? 66'h3fffff00000000000 : 66'b0;
  wire [65:0] sx_term6;
  assign sx_term6 = pp_sign_s1_q[6] ? 66'h3ffffc00000000000 : 66'b0;
  wire [65:0] sx_term7;
  assign sx_term7 = pp_sign_s1_q[7] ? 66'h3ffff000000000000 : 66'b0;
  wire [65:0] sx_term8;
  assign sx_term8 = pp_sign_s1_q[8] ? 66'h3fffc000000000000 : 66'b0;
  wire [65:0] sx_term9;
  assign sx_term9 = pp_sign_s1_q[9] ? 66'h3fff0000000000000 : 66'b0;
  wire [65:0] sx_term10;
  assign sx_term10 = pp_sign_s1_q[10] ? 66'h3ffc0000000000000 : 66'b0;
  wire [65:0] sx_term11;
  assign sx_term11 = pp_sign_s1_q[11] ? 66'h3ff00000000000000 : 66'b0;
  wire [65:0] sx_term12;
  assign sx_term12 = pp_sign_s1_q[12] ? 66'h3fc00000000000000 : 66'b0;
  wire [65:0] sx_term13;
  assign sx_term13 = pp_sign_s1_q[13] ? 66'h3f000000000000000 : 66'b0;
  wire [65:0] sx_term14;
  assign sx_term14 = pp_sign_s1_q[14] ? 66'h3c000000000000000 : 66'b0;
  wire [65:0] sx_term15;
  assign sx_term15 = pp_sign_s1_q[15] ? 66'h30000000000000000 : 66'b0;
  wire [65:0] sx_sum_l0_0;
  assign sx_sum_l0_0 = sx_term0 + sx_term1;
  wire [65:0] sx_sum_l0_1;
  assign sx_sum_l0_1 = sx_term2 + sx_term3;
  wire [65:0] sx_sum_l0_2;
  assign sx_sum_l0_2 = sx_term4 + sx_term5;
  wire [65:0] sx_sum_l0_3;
  assign sx_sum_l0_3 = sx_term6 + sx_term7;
  wire [65:0] sx_sum_l0_4;
  assign sx_sum_l0_4 = sx_term8 + sx_term9;
  wire [65:0] sx_sum_l0_5;
  assign sx_sum_l0_5 = sx_term10 + sx_term11;
  wire [65:0] sx_sum_l0_6;
  assign sx_sum_l0_6 = sx_term12 + sx_term13;
  wire [65:0] sx_sum_l0_7;
  assign sx_sum_l0_7 = sx_term14 + sx_term15;
  wire [65:0] sx_sum_l1_0;
  assign sx_sum_l1_0 = sx_sum_l0_0 + sx_sum_l0_1;
  wire [65:0] sx_sum_l1_1;
  assign sx_sum_l1_1 = sx_sum_l0_2 + sx_sum_l0_3;
  wire [65:0] sx_sum_l1_2;
  assign sx_sum_l1_2 = sx_sum_l0_4 + sx_sum_l0_5;
  wire [65:0] sx_sum_l1_3;
  assign sx_sum_l1_3 = sx_sum_l0_6 + sx_sum_l0_7;
  wire [65:0] sx_sum_l2_0;
  assign sx_sum_l2_0 = sx_sum_l1_0 + sx_sum_l1_1;
  wire [65:0] sx_sum_l2_1;
  assign sx_sum_l2_1 = sx_sum_l1_2 + sx_sum_l1_3;
  wire [65:0] sx_sum_l3_0;
  assign sx_sum_l3_0 = sx_sum_l2_0 + sx_sum_l2_1;
  assign signext_term = sx_sum_l3_0;

  CSA_66 csa_signext (
    .a(wallace_sum_s2_q), .b(wallace_carry_s2_q), .c(signext_term_s2_q),
    .sum_out(csa_sum), .carry_out(csa_carry_raw)
  );
  assign result_full = csa_sum_s3_q + {csa_carry_raw_s3_q[64:0], 1'b0};

  generate
    if (MUL_EXTRA_LATENCY_C == 0) begin : gen_no_extra_mul_latency
      assign result_out = result_s4_q;
      assign done = valid_s4_q;
    end else begin : gen_extra_mul_latency
      reg [63:0] result_extra_q [0:MUL_EXTRA_LATENCY_C-1];
      reg [MUL_EXTRA_LATENCY_C-1:0] valid_extra_q;
      integer extra_i;

      always @(posedge clk or posedge reset) begin
        if (reset) begin
          valid_extra_q <= {MUL_EXTRA_LATENCY_C{1'b0}};
          for (extra_i = 0; extra_i < MUL_EXTRA_LATENCY_C; extra_i = extra_i + 1) begin
            result_extra_q[extra_i] <= 64'b0;
          end
        end else begin
          valid_extra_q[0] <= valid_s4_q;
          result_extra_q[0] <= result_s4_q;
          for (extra_i = 1; extra_i < MUL_EXTRA_LATENCY_C; extra_i = extra_i + 1) begin
            valid_extra_q[extra_i] <= valid_extra_q[extra_i - 1];
            result_extra_q[extra_i] <= result_extra_q[extra_i - 1];
          end
        end
      end

      assign result_out = result_extra_q[MUL_EXTRA_LATENCY_C-1];
      assign done = valid_extra_q[MUL_EXTRA_LATENCY_C-1];
    end
  endgenerate
endmodule
