#!/usr/bin/env python3
"""Generate the EXP16 BDOT.W functional-test assembly source."""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path


MASK32 = 0xFFFF_FFFF
BDOT_BASE = 0xFFFF_8000
RANDOM_SEED = 0xBD07_2026
RANDOM_CASES = 1000
OUTPUT = (
    Path(__file__).resolve().parent
    / "../func/func_src/inst/n0_bdot_w.S"
).resolve()

REG_NAMES = {
    0: "zero",
    4: "a0",
    5: "a1",
    6: "a2",
    7: "a3",
    8: "a4",
    9: "a5",
    10: "a6",
    11: "a7",
    12: "t0",
    13: "t1",
    14: "t2",
    15: "t3",
    16: "t4",
    17: "t5",
    18: "t6",
    19: "t7",
    20: "t8",
    21: "x",
    22: "fp",
}
TEST_REGS = tuple(range(4, 23))


def bdot_w(a: int, b: int) -> int:
    """Return the architectural 32-bit result of BDOT.W."""
    distance = ((a ^ b) & MASK32).bit_count()
    return (32 - 2 * distance) & MASK32


def encode_bdot(rd: int, rj: int, rk: int) -> int:
    for name, value in (("rd", rd), ("rj", rj), ("rk", rk)):
        if not 0 <= value < 32:
            raise ValueError(f"{name} must be in r0..r31")
    return BDOT_BASE | (rk << 10) | (rj << 5) | rd


def hex32(value: int) -> str:
    return f"0x{value & MASK32:08x}"


def emit_case(
    lines: list[str],
    a: int,
    b: int,
    rj: int,
    rk: int,
    rd: int,
    ref: int,
    comment: str | None = None,
) -> None:
    if len({rj, rk, rd, ref}) != 4:
        raise ValueError("ordinary cases require four distinct registers")
    if comment:
        lines.append(f"    // {comment}")
    lines.extend(
        (
            f"    LI ({REG_NAMES[rj]}, {hex32(a)})",
            f"    LI ({REG_NAMES[rk]}, {hex32(b)})",
            f"    LI ({REG_NAMES[ref]}, {hex32(bdot_w(a, b))})",
            f"    .word {hex32(encode_bdot(rd, rj, rk))}",
            f"    bne {REG_NAMES[rd]}, {REG_NAMES[ref]}, inst_error",
        )
    )


def random_pairs() -> list[tuple[int, int]]:
    rng = random.Random(RANDOM_SEED)
    pairs: list[tuple[int, int]] = []
    seen: set[tuple[int, int]] = set()
    while len(pairs) < RANDOM_CASES:
        pair = (rng.getrandbits(32), rng.getrandbits(32))
        if pair not in seen:
            seen.add(pair)
            pairs.append(pair)
    return pairs


def generate() -> str:
    # Lock down the published encoding and reference examples.
    assert encode_bdot(6, 4, 5) == 0xFFFF_9486
    assert bdot_w(0x1234_5678, 0x1234_5678) == 0x0000_0020
    assert bdot_w(0xAAAA_AAAA, 0x5555_5555) == 0xFFFF_FFE0
    assert bdot_w(0xAAAA_AAAA, 0xCCCC_CCCC) == 0
    assert bdot_w(0x1234_5678, 0x1234_5677) == 0x0000_0018

    lines = [
        "/*",
        " * Generated by software/examples/nscscc_func/gen_bdot_w_test.py.",
        " * Regenerate with: python3 -B gen_bdot_w_test.py",
        " * Do not edit this file by hand.",
        f" * Random vectors: {RANDOM_CASES}, seed: {hex32(RANDOM_SEED)}.",
        " */",
        '#include "asm.h"',
        '#include "regdef.h"',
        '#include "inst_test.h"',
        "",
        "LEAF(n0_bdot_w_test)",
        "    addi.w s0, s0, 1",
        "    li.w s2, 0",
        "",
        "    // Capability probe: an unsupported encoding must fail point 1.",
        "    LI_EXIMM(t0, t1, IMM_INE)",
        "    li.w t5, 0",
        "    LI (a0, 0x12345678)",
        "    LI (a1, 0x12345678)",
        "    LI (a2, 0x5a5a5a5a)",
        "    LI (a3, 0x00000020)",
        "    la.local s4, .Lbdot_probe",
        ".Lbdot_probe:",
        f"    .word {hex32(encode_bdot(6, 4, 5))}",
        "    bne s2, zero, inst_error",
        "    bne a2, a3, inst_error",
        "",
        "    // Published functional examples.",
    ]

    examples = (
        (0x1234_5678, 0x1234_5678, "all bits equal: +32"),
        (0xAAAA_AAAA, 0x5555_5555, "all bits different: -32"),
        (0xAAAA_AAAA, 0xCCCC_CCCC, "16 equal and 16 different: 0"),
        (0x1234_5678, 0x1234_5677, "four bits different: +24"),
    )
    for index, (a, b, comment) in enumerate(examples):
        base = 4 * index
        regs = tuple(TEST_REGS[(base + offset) % len(TEST_REGS)] for offset in range(4))
        emit_case(lines, a, b, regs[0], regs[1], regs[2], regs[3], comment)

    lines.extend(("", "    // Every possible Hamming distance and result value."))
    distance_base = 0xA5A5_F00F
    for distance in range(33):
        difference_mask = MASK32 if distance == 32 else (1 << distance) - 1
        b = distance_base ^ difference_mask
        base = 4 * distance
        regs = tuple(TEST_REGS[(base + offset) % len(TEST_REGS)] for offset in range(4))
        emit_case(
            lines,
            distance_base,
            b,
            regs[0],
            regs[1],
            regs[2],
            regs[3],
            f"Hamming distance {distance}",
        )

    lines.extend(
        (
            "",
            "    // r0 as both sources.",
            "    LI (a3, 0x00000020)",
            f"    .word {hex32(encode_bdot(6, 0, 0))}",
            "    bne a2, a3, inst_error",
            "",
            "    // r0 in each source position.",
            "    LI (a1, 0x0000000f)",
            "    LI (a3, 0x00000018)",
            f"    .word {hex32(encode_bdot(6, 0, 5))}",
            "    bne a2, a3, inst_error",
            "    LI (a0, 0x0000000f)",
            f"    .word {hex32(encode_bdot(6, 4, 0))}",
            "    bne a2, a3, inst_error",
            "",
            "    // rd=r0 discards the result and leaves both sources intact.",
            "    LI (a0, 0x13579bdf)",
            "    LI (a1, 0x2468ace0)",
            "    LI (a2, 0x5a5aa5a5)",
            f"    .word {hex32(encode_bdot(0, 4, 5))}",
            "    LI (a3, 0x13579bdf)",
            "    bne a0, a3, inst_error",
            "    LI (a3, 0x2468ace0)",
            "    bne a1, a3, inst_error",
            "    LI (a3, 0x5a5aa5a5)",
            "    bne a2, a3, inst_error",
            "",
            "    // Register overlap: rd=rj, rd=rk, then rd=rj=rk.",
            "    LI (a0, 0x12345678)",
            "    LI (a1, 0x12345677)",
            f"    .word {hex32(encode_bdot(4, 4, 5))}",
            "    LI (a3, 0x00000018)",
            "    bne a0, a3, inst_error",
            "    LI (a0, 0xaaaaaaaa)",
            "    LI (a1, 0x55555555)",
            f"    .word {hex32(encode_bdot(5, 4, 5))}",
            "    LI (a3, 0xffffffe0)",
            "    bne a1, a3, inst_error",
            "    LI (a0, 0x89abcdef)",
            f"    .word {hex32(encode_bdot(4, 4, 4))}",
            "    LI (a3, 0x00000020)",
            "    bne a0, a3, inst_error",
            "",
            "    // Immediate BDOT.W-to-ADD.W dependency.",
            "    LI (a0, 0x12345678)",
            "    LI (a1, 0x12345678)",
            "    LI (a4, 0x00000005)",
            f"    .word {hex32(encode_bdot(6, 4, 5))}",
            "    add.w a5, a2, a4",
            "    LI (a3, 0x00000025)",
            "    bne a5, a3, inst_error",
            "",
            "    // Immediate BDOT.W-to-SUB.W dependency.",
            "    LI (a0, 0xaaaaaaaa)",
            "    LI (a1, 0x55555555)",
            "    LI (a4, 0x00000005)",
            f"    .word {hex32(encode_bdot(6, 4, 5))}",
            "    sub.w a5, a2, a4",
            "    LI (a3, 0xffffffdb)",
            "    bne a5, a3, inst_error",
            "",
            "    // Immediate BDOT.W-to-BDOT.W dependency.",
            "    LI (a0, 0x12345678)",
            "    LI (a1, 0x12345677)",
            "    LI (a4, 0x00000000)",
            f"    .word {hex32(encode_bdot(6, 4, 5))}",
            f"    .word {hex32(encode_bdot(9, 6, 8))}",
            f"    LI (a3, {hex32(bdot_w(bdot_w(0x12345678, 0x12345677), 0))})",
            "    bne a5, a3, inst_error",
            "",
            "    // Immediate BDOT.W-to-BEQ dependency.",
            "    LI (a0, 0x0f0f0f0f)",
            "    LI (a1, 0x00ff00ff)",
            f"    LI (a3, {hex32(bdot_w(0x0F0F0F0F, 0x00FF00FF))})",
            f"    .word {hex32(encode_bdot(6, 4, 5))}",
            "    beq a2, a3, .Lbdot_branch_dependency_ok",
            "    b inst_error",
            ".Lbdot_branch_dependency_ok:",
            "",
            "    // A BDOT.W on a flushed branch path must not write back.",
            "    LI (a0, 0x12345678)",
            "    LI (a1, 0x87654321)",
            "    LI (s8, 0x55aa33cc)",
            "    beq a0, a0, .Lbdot_flush_ok",
            f"    .word {hex32(encode_bdot(31, 4, 5))}",
            ".Lbdot_flush_ok:",
            "    addi.w zero, zero, 0",
            "    addi.w zero, zero, 0",
            "    addi.w zero, zero, 0",
            "    addi.w zero, zero, 0",
            "    addi.w zero, zero, 0",
            "",
            "    // BDOT.W is non-privileged and must execute at PLV3.",
            "    LI (a0, 0x12345678)",
            "    LI (a1, 0x12345677)",
            "    LI (a2, 0x5a5a5a5a)",
            "    LI (a3, 0x00000018)",
            "    LI_EXIMM(t0, t1, IMM_SYSCALL)",
            "    li.w s2, 0",
            "    li.w t5, 0x3",
            "    li.w t0, 0x3",
            "    li.w t1, 0x7",
            "    csrxchg t0, t1, csr_crmd",
            f"    .word {hex32(encode_bdot(6, 4, 5))}",
            "    la.local s4, .Lbdot_plv3_syscall",
            ".Lbdot_plv3_syscall:",
            "    syscall 0",
            "    lu12i.w t0, 0x10",
            "    bne s2, t0, inst_error",
            "    bne a2, a3, inst_error",
            "    LI_EXIMM(t0, t1, IMM_KERNEL)",
            "    syscall 0",
            "    csrrd t0, csr_crmd",
            "    andi t0, t0, 0x7",
            "    bne t0, zero, inst_error",
            "    li.w s2, 0",
            "    li.w t5, 0",
            "    LI_EXIMM(t0, t1, IMM_INE)",
            "",
            f"    // {RANDOM_CASES} deterministic random reference-model cases.",
        )
    )

    for index, (a, b) in enumerate(random_pairs()):
        base = 4 * index
        regs = tuple(TEST_REGS[(base + offset) % len(TEST_REGS)] for offset in range(4))
        emit_case(lines, a, b, regs[0], regs[1], regs[2], regs[3])

    lines.extend(
        (
            "",
            "    // Check the flushed destination after ample time for any late writeback.",
            "    LI (t0, 0x55aa33cc)",
            "    bne s8, t0, inst_error",
            "    bne s2, zero, inst_error",
            "    LI_EXIMM(t0, t1, IMM_NONE)",
            "    addi.w s3, s3, 1",
            "inst_error:",
            "    slli.w t1, s0, 24",
            "    or t0, t1, s3",
            "    st.w t0, s1, 0",
            "    jirl zero, ra, 0",
            "END(n0_bdot_w_test)",
            "",
        )
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed assembly differs from regenerated output",
    )
    args = parser.parse_args()
    generated = generate()

    if args.check:
        try:
            current = OUTPUT.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated file: {OUTPUT}", file=sys.stderr)
            return 1
        if current != generated:
            print(
                f"{OUTPUT} is stale; run python3 -B {Path(__file__).name}",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"generated {OUTPUT} ({RANDOM_CASES} random vectors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
